<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/static/main.css" />
    <title>
      Passbook for Developers
    </title>
  </head>
  <body>
    {{ page_header }}
    <div align="center">
    <p><a href="http://mactech-passbook.appspot.com/passes/mactech.pkpass"><img src="http://mactech-passbook.appspot.com/static/Add_to_Passbook_US_UK.svg"></a></p>
    </div>
    
    <h1>
      Passbook for Developers
    </h1>
    <h3>
        Author: Philippe Casgrain, <a href="http://twitter.com/philippec">@philippec</a>
    </h3>
    <h2>
        Pre-requisites
    </h2>
    <ul>
        <li>
            <a href="https://developer.apple.com/devcenter/ios/index.action">Apple iOS Developer account</a>
        </li>
        <li>
            (Optional) <a href="https://appengine.google.com/">Google App Engine account</a> (to run a server)<br>
            <em>Requires a free Google account and a SMS-enabled phone.</em>
        </li>
        <li>
            (Optional) <a href="http://urbanairship.com">Urban Airship account</a> (to send push notifications)<br>
            <em>Sign up for the "Developer" plan, which is free.</em>
        </li>
        <li>
            (Optional) <a href="https://developer.apple.com/xcode/">Xcode</a> (to build the 'signpass' tool)
        </li>
    </ul>
    <h2>
        Resources
    </h2>
    <ul>
        <li>
            <a href="https://github.com/philippec/MacTech2013">Source for this presentation</a>
        </li>
        <li>
            <a href="https://developer.apple.com/passbook/">Apple Sample Code</a>
        </li>
    </ul>
    <h2>
        To create a pass
    </h2>
    <ul>
        <li>
            Create a pass-signing certificate at <a href="https://developer.apple.com/account/ios/certificate/certificateList.action">developer.apple.com</a>
        </li>
        <li>
            Modify the sample MacTech pass (from the <a href="https://github.com/philippec/MacTech2013">Github repository</a>) with your Team ID and your pass identifier
        </li>
        <li>
            Build the 'signpass' command-line application
        </li>
        <li>
            Sign your pass with <code>./signpass -p MacTech.raw -o mactech.pkpass </code>
        </li>
        <li>
            Drag <code>mactech.pkpass</code> in the Simulator to check it
        </li>
    </ul>
    <h2>
        To distribute a pass
    </h2>
    <ul>
        <li>
            Send it via email, iMessage or AirDrop
        </li>
        <li>
            Store it on your webserver and distribute the URL<br>
            <em>Make sure to set the mime-type to "application/vnd.apple.pkpass"</em>
        </li>
        <li>
            Build the Google App Engine server from the sample code.
            <ul>
                <li>
                    Change the name in <code>app.yaml</code> from 'mactech-passbook' to your Google App Engine name
                </li>
                <li>
                    Sign your pass with <code>./signpass -p MacTech.raw -o ../server/mactech.pkpass </code>
                </li>
                <li>
                    Deploy from the Google App Engine console and download at <code>https://yourappname.appspot.com/passes/mactech.pkpass</code>
                </li>
            </ul>
        </li>
    </ul>
    <h2>
        To use push notifications
    </h2>
    <h3>
        First, you must set up Push Notifications by hooking up your Google App Engine app to Urban Airship
    </h3>
    <ul>
        <li>
            Create a "Production" project in the Urban Airship dashboard
        </li>
        <li>
            Export your certificate & private key into a p12 file with a password
        </li>
        <li>
            Import this certificate in Urban Airship to give it permission to create push notifications on your behalf
        </li>
        <li>
            Enter the correct App Key and App Master Key in PrivateInfo.py. They can be found in the Urban Airship control panel under Settings > API Keys
        </li>
    </ul>
    <h3>
        Next, use Urban Airship to send push notifications
    </h3>
    <ul>
        <li>
            Create a message in Urban Airship's "Messages > +New Push Message"
        </li>
        <li>
            Send a message. I use <code>sound : "ignored"</code> to send an empty message
        </li>
    </ul>
    Your messages are now delivered, and your passes are updating.

    {{ page_footer }}
  </body>
</html>
