<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/static/main.css" />
    <title>
      Passbook for Developers
    </title>
  </head>
  <body>
    {{ page_header }}
    <h1>
      Passbook for Developers
    </h1>
    <h2>
        Pre-requisites
    </h2>
    <ul>
        <li>
            <a href="https://developer.apple.com/devcenter/ios/index.action">Apple iOS Developer account</a>
        </li>
        <li>
            (Optional) <a href="https://appengine.google.com/">Google App Engine account</a>
        </li>
        <li>
            (Optional) <a href="http://urbanairship.com">Urban Airship account</a>
        </li>
    </ul>
    <h2>
        Resources
    </h2>
    <ul>
        <li>
            <a href="https://github.com/philippec/MacTech2013">Source for this presentation</a>
        </li>
        <li>
            <a href="https://developer.apple.com/passbook/">Apple Sample Code</a>
        </li>
    </ul>
    <h2>
        To create a pass
    </h2>
    <ul>
        <li>
            Create a pass-signing certificate at <a href="https://developer.apple.com/account/ios/certificate/certificateList.action">developer.apple.com</a>
        </li>
        <li>
            Modify the sample pass with your Team ID and your pass identifier
        </li>
        <li>
            Build the 'signpass' command-line application
        </li>
        <li>
            Sign your pass with <code>./signpass -p MacTech.raw -o mactech.pkpass </code>
        </li>
        <li>
            Drag <code>mactech.pkpass</code> in the Simulator to check it
        </li>
    </ul>
    <h2>
        To distribute a pass
    </h2>
    <ul>
        <li>
            Send it via email or iMessage
        </li>
        <li>
            Store it on your webserver and distribute the URL<br>
            Make sure to set the mime-type to "application/vnd.apple.pkpass"
        </li>
        <li>
            Build the Google App Engine server from the sample code.
            <ul>
                <li>
                    Change the name in <code>app.yaml</code> from 'mactech-passbook' to your Google App Engine name
                </li>
                <li>
                    Sign your pass with <code>./signpass -p MacTech.raw -o ../server/mactech.pkpass </code>
                </li>
                <li>
                    Deploy from the Google App Engine console and download at https://yourappname.appspot.com/passes/mactech.pkpass
                </li>
            </ul>
        </li>
    </ul>
    <h2>
        To use push notifications
    </h2>
    <ul>
        <li>
            TODO
        </li>
    </ul>

    {{ page_footer }}
  </body>
</html>
